/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

const glowBlue = new THREE.MeshBasicMaterial({
  color: new THREE.Color(18, 15, 55),
  toneMapped: false,
});

const glowGreen = new THREE.MeshBasicMaterial({
  color: new THREE.Color(2, 15, 1),
  toneMapped: false,
  opacity: 0.1,
});

const glowRed = new THREE.MeshBasicMaterial({
  color: new THREE.Color(25, 5, 1),
  toneMapped: false,
});

export const Model = (props) => {
  const { nodes, materials } = useGLTF("/cyberEyeDraco.gltf");
  const ref = useRef(null);

  let lerpVal = 0.1;

  useFrame((state) => {
    if (props.active) {
      ref.current.rotation.x += 0.00025;
      ref.current.rotation.y += 0.0005;
    } else {
      let rotY = THREE.MathUtils.degToRad(state.mouse.x) * -40;
      let rotX = THREE.MathUtils.degToRad(state.mouse.y) * -40;

      ref.current.rotation.y = THREE.MathUtils.lerp(
        ref.current.rotation.y,
        rotY,
        lerpVal
      );
      ref.current.rotation.x = THREE.MathUtils.lerp(
        ref.current.rotation.x,
        rotX,
        lerpVal
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.78, 0.16]} ref={ref}>
        <group position={[0, 294.87, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group
            position={[0, 241.46, -294.87]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.19}>
            <mesh geometry={nodes.ID2322.geometry} material={materials.Mat} />
            <mesh
              geometry={nodes.ID2322_1.geometry}
              material={props.active ? glowGreen : glowBlue}
            />
          </group>
        </group>
        <group position={[0, 0, -214.85]} scale={0.38}>
          <group position={[0, 0, -11.94]} rotation={[0, 0, 0.43]}>
            <mesh
              geometry={nodes.Zylinder11.geometry}
              material={materials["Material.003"]}
              position={[-75.65, -257.62, 0]}
              rotation={[0, 0, -0.29]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere021.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder110.geometry}
              material={materials["Material.003"]}
              position={[-75.65, 257.62, 0]}
              rotation={[0, 0, -2.86]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere012.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder111.geometry}
              material={materials["Material.003"]}
              position={[0, 268.5, 0]}
              rotation={[0, 0, Math.PI]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere011.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder112.geometry}
              material={materials["Material.003"]}
              position={[75.65, 257.62, 0]}
              rotation={[0, 0, 2.86]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere010.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder113.geometry}
              material={materials["Material.003"]}
              position={[145.16, 225.88, 0]}
              rotation={[0, 0, 2.57]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere009.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder114.geometry}
              material={materials["Material.003"]}
              position={[202.92, 175.83, 0]}
              rotation={[0, 0, 2.28]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere008.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder115.geometry}
              material={materials["Material.003"]}
              position={[244.24, 111.54, 0]}
              rotation={[0, 0, 2]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere007.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder116.geometry}
              material={materials["Material.003"]}
              position={[265.77, 38.21, 0]}
              rotation={[0, 0, 1.71]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere006.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder117.geometry}
              material={materials["Material.003"]}
              position={[265.77, -38.21, 0]}
              rotation={[0, 0, 1.43]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere005.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder118.geometry}
              material={materials["Material.003"]}
              position={[244.24, -111.54, 0]}
              rotation={[0, 0, 1.14]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere004.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder119.geometry}
              material={materials["Material.003"]}
              position={[202.92, -175.83, 0]}
              rotation={[0, 0, 0.86]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere003.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder12.geometry}
              material={materials["Material.003"]}
              position={[-145.16, -225.88, 0]}
              rotation={[0, 0, -0.57]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere020.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder120.geometry}
              material={materials["Material.003"]}
              position={[145.16, -225.88, 0]}
              rotation={[0, 0, 0.57]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere002.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder121.geometry}
              material={materials["Material.003"]}
              position={[75.65, -257.62, 0]}
              rotation={[0, 0, 0.29]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere001.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder122.geometry}
              material={materials["Material.003"]}
              position={[0, -268.5, 0]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder13.geometry}
              material={materials["Material.003"]}
              position={[-202.92, -175.83, 0]}
              rotation={[0, 0, -0.86]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere019.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder14.geometry}
              material={materials["Material.003"]}
              position={[-244.24, -111.54, 0]}
              rotation={[0, 0, -1.14]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere018.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder15.geometry}
              material={materials["Material.003"]}
              position={[-265.77, -38.21, 0]}
              rotation={[0, 0, -1.43]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere017.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder16.geometry}
              material={materials["Material.003"]}
              position={[-265.77, 38.21, 0]}
              rotation={[0, 0, -1.71]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere016.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder17.geometry}
              material={materials["Material.003"]}
              position={[-244.24, 111.54, 0]}
              rotation={[0, 0, -2]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere015.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder18.geometry}
              material={materials["Material.003"]}
              position={[-202.92, 175.83, 0]}
              rotation={[0, 0, -2.28]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere014.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
            <mesh
              geometry={nodes.Zylinder19.geometry}
              material={materials["Material.003"]}
              position={[-145.16, 225.88, 0]}
              rotation={[0, 0, -2.57]}
              scale={0.42}>
              <mesh
                geometry={nodes.Sphere013.geometry}
                material={materials["Material.003"]}
                position={[1.76, -0.58, -12.48]}
                rotation={[-1.57, -1.25, -1.84]}
                scale={[0.32, 0.32, 0.51]}
              />
            </mesh>
          </group>
          <group position={[0, 0, 3.52]} scale={2.64}>
            <mesh
              geometry={nodes.Würfel_0.geometry}
              material={materials["Mat.017"]}
              position={[0, -101, 0]}
              rotation={[0, 0, 0.4]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder002.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder1.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_1.geometry}
              material={materials["Mat.017"]}
              position={[54.6, -84.97, 0]}
              rotation={[0, 0, 0.97]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder003.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder004.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_10.geometry}
              material={materials["Mat.017"]}
              position={[-54.6, -84.97, 0]}
              rotation={[0, 0, -0.17]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder021.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder022.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_2.geometry}
              material={materials["Mat.017"]}
              position={[91.87, -41.96, 0]}
              rotation={[0, 0, 1.54]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder005.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder006.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_3.geometry}
              material={materials["Mat.017"]}
              position={[99.97, 14.37, 0]}
              rotation={[0, 0, 2.12]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder007.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder008.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_4.geometry}
              material={materials["Mat.017"]}
              position={[76.33, 66.14, 0]}
              rotation={[0, 0, 2.69]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder009.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder010.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_5.geometry}
              material={materials["Mat.017"]}
              position={[28.46, 96.91, 0]}
              rotation={[0, 0, -3.03]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder011.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder012.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_6.geometry}
              material={materials["Mat.017"]}
              position={[-28.46, 96.91, 0]}
              rotation={[0, 0, -2.45]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder013.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder014.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_7.geometry}
              material={materials["Mat.017"]}
              position={[-76.33, 66.14, 0]}
              rotation={[0, 0, -1.88]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder015.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder016.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_8.geometry}
              material={materials["Mat.017"]}
              position={[-99.97, 14.37, 0]}
              rotation={[0, 0, -1.31]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder017.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder018.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_9.geometry}
              material={materials["Mat.017"]}
              position={[-91.87, -41.96, 0]}
              rotation={[0, 0, -0.74]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder019.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder020.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
          </group>
          <group position={[0, 0, 13.96]} rotation={[0, 0, 0.29]} scale={2.64}>
            <mesh
              geometry={nodes.Würfel_0001.geometry}
              material={materials["Mat.017"]}
              position={[0, -101, 0]}
              rotation={[0, 0, 0.4]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder023.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder024.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_1001.geometry}
              material={materials["Mat.017"]}
              position={[54.6, -84.97, 0]}
              rotation={[0, 0, 0.97]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder025.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder026.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_10001.geometry}
              material={materials["Mat.017"]}
              position={[-54.6, -84.97, 0]}
              rotation={[0, 0, -0.17]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder043.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder044.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_2001.geometry}
              material={materials["Mat.017"]}
              position={[91.87, -41.96, 0]}
              rotation={[0, 0, 1.54]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder027.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder028.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_3001.geometry}
              material={materials["Mat.017"]}
              position={[99.97, 14.37, 0]}
              rotation={[0, 0, 2.12]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder029.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder030.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_4001.geometry}
              material={materials["Mat.017"]}
              position={[76.33, 66.14, 0]}
              rotation={[0, 0, 2.69]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder031.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder032.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_5001.geometry}
              material={materials["Mat.017"]}
              position={[28.46, 96.91, 0]}
              rotation={[0, 0, -3.03]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder033.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder034.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_6001.geometry}
              material={materials["Mat.017"]}
              position={[-28.46, 96.91, 0]}
              rotation={[0, 0, -2.45]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder035.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder036.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_7001.geometry}
              material={materials["Mat.017"]}
              position={[-76.33, 66.14, 0]}
              rotation={[0, 0, -1.88]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder037.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder038.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_8001.geometry}
              material={materials["Mat.017"]}
              position={[-99.97, 14.37, 0]}
              rotation={[0, 0, -1.31]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder039.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder040.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
            <mesh
              geometry={nodes.Würfel_9001.geometry}
              material={materials["Mat.017"]}
              position={[-91.87, -41.96, 0]}
              rotation={[0, 0, -0.74]}
              scale={0.38}>
              <mesh
                geometry={nodes.Zylinder041.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-16, -9.58, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
              <mesh
                geometry={nodes.Zylinder042.geometry}
                material={materials["Metal_-_Chrome"]}
                position={[-0.04, -0.01, 4.92]}
                rotation={[0, 0, 0.2]}
                scale={[0.16, 0.16, 0.26]}
              />
            </mesh>
          </group>
          <mesh
            geometry={nodes.Röhre1.geometry}
            material={materials["Mat.016"]}
            position={[0, 0, 28.23]}
          />
          <mesh
            geometry={nodes.Torus.geometry}
            material={materials["Metal_-_Chrome"]}
            position={[0, 0, -16.78]}
          />
          <mesh
            geometry={nodes.Tube.geometry}
            material={materials["Mat.016"]}
            position={[0, 0, -5.58]}
          />
        </group>
        <group
          position={[0, 0, -82.56]}
          rotation={[-Math.PI, 0, -2.48]}
          scale={[3.83, 3.83, 1.14]}>
          <mesh
            geometry={nodes.Kugel.geometry}
            material={materials["default"]}
            position={[0, 0, -47.13]}
            scale={[0.3, 0.3, 0.05]}
          />
          <mesh
            geometry={nodes.Kugel001.geometry}
            material={materials["default"]}
            position={[0, 0, -35.6]}
            scale={[0.3, 0.3, 0.05]}
          />
          <mesh
            geometry={nodes.Kugel002.geometry}
            material={materials["default"]}
            position={[0, 0, -21.83]}
            scale={[0.3, 0.3, 0.07]}
          />
          <mesh
            geometry={nodes["Lathe-NURBS1"].geometry}
            material={materials["Glas.003"]}
            position={[0, 0, 57.44]}
            rotation={[-Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes["Lathe-NURBS2"].geometry}
            material={materials["default"]}
            position={[0, 0, 9.77]}
            rotation={[-Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes["Lathe-NURBS3"].geometry}
            material={materials["default"]}
            position={[0, 0, 63.46]}
          />
          <mesh
            geometry={nodes["Lathe-NURBS4"].geometry}
            material={materials["default"]}
            position={[0, 0, -5.21]}
            rotation={[-Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes["Lathe-NURBS6"].geometry}
            material={materials["default"]}
            position={[0, 0, -17.92]}
            rotation={[-Math.PI, 0, 0]}
            scale={[1, 1, 0.65]}
          />
        </group>
        <group position={[0, 0, 244.28]} scale={1.19}>
          <group
            position={[148, 0, 0]}
            rotation={[0, 0, Math.PI / 2]}
            scale={0.84}>
            <group position={[0, 529.01, -54.94]} rotation={[-1.2, 0, 0]}>
              <mesh
                geometry={nodes.Würfel002.geometry}
                material={materials["Material.001"]}
                position={[0, -320.07, -447.82]}
              />
            </group>
            <mesh
              geometry={nodes.Torus003.geometry}
              material={materials["Metal_-_Chrome"]}
              position={[0, 164.3, 64.27]}
              rotation={[0.37, 0, -1.37]}
            />
          </group>
          <group position={[0, -148, 0]} scale={0.84}>
            <group position={[0, 529.01, -54.94]} rotation={[-1.2, 0, 0]}>
              <mesh
                geometry={nodes.Würfel001.geometry}
                material={materials["Material.001"]}
                position={[0, -320.07, -447.82]}
              />
            </group>
            <mesh
              geometry={nodes.Torus002.geometry}
              material={materials["Metal_-_Chrome"]}
              position={[0, 164.3, 64.27]}
              rotation={[0.37, 0, -1.37]}
            />
          </group>
          <group
            position={[-148, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.84}>
            <group position={[0, 529.01, -54.94]} rotation={[-1.2, 0, 0]}>
              <mesh
                geometry={nodes.Würfel003.geometry}
                material={materials["Material.001"]}
                position={[0, -320.07, -447.82]}
              />
            </group>
            <mesh
              geometry={nodes.Torus004.geometry}
              material={materials["Metal_-_Chrome"]}
              position={[0, 164.3, 64.27]}
              rotation={[0.37, 0, -1.37]}
            />
          </group>
          <group position={[0, 148, 0]} rotation={[0, 0, Math.PI]} scale={0.84}>
            <group position={[0, 529.01, -54.94]} rotation={[-1.2, 0, 0]}>
              <mesh
                geometry={nodes.Würfel.geometry}
                material={materials["Material.001"]}
                position={[0, -320.07, -447.82]}
              />
            </group>
            <mesh
              geometry={nodes.Torus001.geometry}
              material={materials["Metal_-_Chrome"]}
              position={[0, 164.3, 64.27]}
              rotation={[0.37, 0, -1.37]}
            />
          </group>
        </group>
        <group
          position={[0, 0.15, 292.25]}
          rotation={[Math.PI, 0, 0]}
          scale={0.07}>
          <mesh
            geometry={nodes.Isolation.geometry}
            material={materials["Glas.1"]}>
            <mesh
              geometry={nodes.Cap_1.geometry}
              material={materials["Glas.1"]}
              rotation={[-Math.PI / 2, 0, -3.11]}
            />
            <mesh
              geometry={nodes.Cap_2.geometry}
              material={materials["Glas.1"]}
              position={[-79.66, 0, -4497.76]}
              rotation={[-Math.PI / 2, 0, -3.01]}
            />
          </mesh>
          <mesh geometry={nodes.Sweep.geometry} material={materials["Mat.013"]}>
            <mesh
              geometry={nodes.Cap_1002.geometry}
              material={materials["Mat.013"]}
              rotation={[-Math.PI / 2, 0, -3.11]}
            />
            <mesh
              geometry={nodes.Cap_2002.geometry}
              material={materials["Mat.013"]}
              position={[-79.66, 0, -4497.76]}
              rotation={[-Math.PI / 2, 0, -3.01]}
            />
          </mesh>
          <mesh
            geometry={nodes["Sweep-NURBS1"].geometry}
            material={materials["Mat.24"]}>
            <mesh
              geometry={nodes.Cap_1001.geometry}
              material={materials["Mat.24"]}
              rotation={[-Math.PI / 2, 0, -3.11]}
            />
            <mesh
              geometry={nodes.Cap_2001.geometry}
              material={materials["Mat.24"]}
              position={[-79.66, 0, -4497.76]}
              rotation={[-Math.PI / 2, 0, -3.01]}
            />
          </mesh>
        </group>
        <group
          position={[0, 44.16, 714.43]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.05}>
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={materials["Material.002"]}
            position={[0, 0, -41.81]}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes.Blei.geometry}
            material={materials["Mat.3"]}
            position={[0, 0, -41.81]}
            rotation={[0, -1.57, 0]}
            scale={1.6}
          />
        </group>
        <group
          position={[0, 0, -241.46]}
          rotation={[0, 0, Math.PI]}
          scale={1.19}>
          <group
            position={[-242.25, -47.09, 202.09]}
            rotation={[1.57, -1.38, Math.PI]}
            scale={0.84}>
            <mesh
              geometry={nodes.Lathe001.geometry}
              material={materials.Material}
              position={[0.23, -16.16, -294.91]}
              rotation={[Math.PI / 2, 0, -0.04]}
            />
          </group>
        </group>
        <group
          position={[0, 0, -241.46]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.19}>
          <group
            position={[-242.25, -47.09, 202.09]}
            rotation={[1.57, -1.38, Math.PI]}
            scale={0.84}>
            <mesh
              geometry={nodes.Lathe002.geometry}
              material={materials.Material}
              position={[-0.04, -16.16, -295.09]}
              rotation={[Math.PI / 2, 0, -0.04]}
            />
          </group>
        </group>
        <group position={[0, 0, -241.46]} scale={1.19}>
          <group
            position={[-242.25, -47.09, 202.09]}
            rotation={[1.57, -1.38, Math.PI]}
            scale={0.84}>
            <mesh
              geometry={nodes.Lathe.geometry}
              material={materials.Material}
              position={[-0.22, -16.16, -294.83]}
              rotation={[Math.PI / 2, 0, -0.04]}
            />
          </group>
        </group>
        <group
          position={[0, 0, -241.46]}
          rotation={[0, 0, Math.PI / 2]}
          scale={1.19}>
          <group
            position={[-242.25, -47.09, 202.09]}
            rotation={[1.57, -1.38, Math.PI]}
            scale={0.84}>
            <mesh
              geometry={nodes.Lathe003.geometry}
              material={materials.Material}
              position={[0.04, -16.16, -294.64]}
              rotation={[Math.PI / 2, 0, -0.04]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.Aussenlinse.geometry}
          material={materials["Glas.003"]}
          position={[0, 0, -241.46]}
          scale={1.19}
        />
        <mesh
          geometry={nodes.Innenlinse.geometry}
          material={materials["Glas.003"]}
          position={[0, 0, -222.51]}
          scale={1.19}
        />
        <mesh
          geometry={nodes.Nervstöpsel.geometry}
          material={materials["Mat.018"]}
          position={[0, 0, -241.46]}
          scale={1.19}
        />
        <mesh
          geometry={nodes.Neuroconnectors.geometry}
          material={materials["Mat.002"]}
          position={[0, 0.09, 883.75]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.34, 0.37, 0.34]}>
          <mesh
            geometry={nodes.Sphere022.geometry}
            material={glowBlue}
            position={[95.25, -620.44, 90.21]}
          />
          <mesh
            geometry={nodes.Sphere023.geometry}
            material={glowBlue}
            position={[191.83, -458.13, -169.98]}
          />
          <mesh
            geometry={nodes.Sphere024.geometry}
            material={glowBlue}
            position={[7.91, -1180, -134.78]}
          />
          <mesh
            geometry={nodes.Sphere025.geometry}
            material={glowBlue}
            position={[31.11, -1052.49, 107.15]}
          />
          <mesh
            geometry={nodes.Sphere026.geometry}
            material={glowBlue}
            position={[108.74, -1170.89, 123.37]}
          />
          <mesh
            geometry={nodes.Sphere027.geometry}
            material={glowBlue}
            position={[-169.93, -1217.41, 31.25]}
          />
          <mesh
            geometry={nodes.Sphere028.geometry}
            material={glowBlue}
            position={[295.72, -644.38, 48.4]}
          />
          <mesh
            geometry={nodes.Sphere029.geometry}
            material={glowBlue}
            position={[8.93, -1625.18, -147.27]}
          />
          <mesh
            geometry={nodes.Sphere030.geometry}
            material={glowBlue}
            position={[-152.37, -981.81, 111.2]}
          />
          <mesh
            geometry={nodes.Sphere031.geometry}
            material={glowBlue}
            position={[-142.8, -602.39, -166.94]}
          />
          <mesh
            geometry={nodes.Sphere032.geometry}
            material={glowBlue}
            position={[-82.31, -911.47, 123.98]}
          />
          <mesh
            geometry={nodes.Sphere033.geometry}
            material={glowBlue}
            position={[-225.75, -764.39, -14.87]}
          />
          <mesh
            geometry={nodes.Sphere034.geometry}
            material={glowBlue}
            position={[-154.17, -765.34, 134.16]}
          />
          <mesh
            geometry={nodes.Sphere035.geometry}
            material={glowBlue}
            position={[27.98, -590.98, 173.78]}
          />
          <mesh
            geometry={nodes.Sphere036.geometry}
            material={glowBlue}
            position={[-194.99, -437.06, 173.39]}
          />
          <mesh
            geometry={nodes.Sphere037.geometry}
            material={glowBlue}
            position={[-87.64, -641.61, -172.59]}
          />
          <mesh
            geometry={nodes.Sphere038.geometry}
            material={glowBlue}
            position={[153.99, -922.94, -12.18]}
          />
          <mesh
            geometry={nodes.Sphere039.geometry}
            material={glowBlue}
            position={[-157.15, -667.48, -178.45]}
          />
          <mesh
            geometry={nodes.Sphere040.geometry}
            material={glowBlue}
            position={[1.47, -797, -149.05]}
          />
          <mesh
            geometry={nodes.Sphere041.geometry}
            material={glowBlue}
            position={[10.33, -912.1, -234.59]}
          />
          <mesh
            geometry={nodes.Sphere042.geometry}
            material={glowBlue}
            position={[144.8, -1349.21, -35.48]}
          />
          <mesh
            geometry={nodes.Sphere043.geometry}
            material={glowBlue}
            position={[-83.3, -812.93, -244.32]}
          />
          <mesh
            geometry={nodes.Sphere044.geometry}
            material={glowBlue}
            position={[-81.74, -444.92, -201.69]}
          />
          <mesh
            geometry={nodes.Sphere045.geometry}
            material={glowBlue}
            position={[-132.44, -533.53, -157.98]}
          />
          <mesh
            geometry={nodes.Sphere046.geometry}
            material={glowBlue}
            position={[174.68, -310.27, 153.12]}
          />
          <mesh
            geometry={nodes.Sphere047.geometry}
            material={glowBlue}
            position={[187.89, -992.61, -11.21]}
          />
          <mesh
            geometry={nodes.Sphere048.geometry}
            material={glowBlue}
            position={[-107.45, -370.66, 87.42]}
          />
          <mesh
            geometry={nodes.Sphere049.geometry}
            material={glowBlue}
            position={[84.63, -1304.41, -84.71]}
          />
          <mesh
            geometry={nodes.Sphere050.geometry}
            material={glowBlue}
            position={[35.66, -1141.76, -167.48]}
          />
          <mesh
            geometry={nodes.Sphere051.geometry}
            material={glowBlue}
            position={[-101.08, -650.92, -60.28]}
          />
          <mesh
            geometry={nodes.Sphere052.geometry}
            material={glowBlue}
            position={[128.41, -585.74, -103.13]}
          />
          <mesh
            geometry={nodes.Sphere053.geometry}
            material={glowBlue}
            position={[-161.37, -450.07, 148.06]}
          />
          <mesh
            geometry={nodes.Sphere054.geometry}
            material={glowBlue}
            position={[125.24, -906.34, -27.43]}
          />
          <mesh
            geometry={nodes.Sphere055.geometry}
            material={glowBlue}
            position={[-7.6, -476.2, -131.7]}
          />
          <mesh
            geometry={nodes.Sphere056.geometry}
            material={glowBlue}
            position={[-22.32, -348.02, -237.76]}
          />
          <mesh
            geometry={nodes.Sphere057.geometry}
            material={glowBlue}
            position={[125.07, -1042.51, 81.28]}
          />
          <mesh
            geometry={nodes.Sphere058.geometry}
            material={glowBlue}
            position={[157.23, -1055.1, -35.15]}
          />
          <mesh
            geometry={nodes.Sphere059.geometry}
            material={glowBlue}
            position={[-181.17, -807.82, -75.93]}
          />
          <mesh
            geometry={nodes.Sphere060.geometry}
            material={glowBlue}
            position={[-164.13, -631.7, -60.79]}
          />
          <mesh
            geometry={nodes.Sphere061.geometry}
            material={glowBlue}
            position={[250.21, -835.42, 44.85]}
          />
          <mesh
            geometry={nodes.Sphere062.geometry}
            material={glowBlue}
            position={[113, -298.61, 184.57]}
          />
          <mesh
            geometry={nodes.Sphere063.geometry}
            material={glowBlue}
            position={[-205.95, -458.5, 66.8]}
          />
          <mesh
            geometry={nodes.Sphere064.geometry}
            material={glowBlue}
            position={[214.91, -521.77, 109.95]}
          />
          <mesh
            geometry={nodes.Sphere065.geometry}
            material={glowBlue}
            position={[-155.12, -410, 277.53]}
          />
          <mesh
            geometry={nodes.Sphere066.geometry}
            material={glowBlue}
            position={[-124.32, -451, -87.49]}
          />
          <mesh
            geometry={nodes.Sphere067.geometry}
            material={glowBlue}
            position={[-74.68, -677.95, -204.81]}
          />
          <mesh
            geometry={nodes.Sphere068.geometry}
            material={glowBlue}
            position={[143.15, -780.71, 88.01]}
          />
          <mesh
            geometry={nodes.Sphere069.geometry}
            material={glowBlue}
            position={[-64.36, -1194.59, 89.61]}
          />
          <mesh
            geometry={nodes.Sphere070.geometry}
            material={glowBlue}
            position={[77.7, -626.48, 69.05]}
          />
          <mesh
            geometry={nodes.Sphere071.geometry}
            material={glowBlue}
            position={[-144.83, -875.16, -102.31]}
          />
          <mesh
            geometry={nodes.Sphere072.geometry}
            material={glowBlue}
            position={[174.9, -429.21, -264.1]}
          />
          <mesh
            geometry={nodes.Sphere073.geometry}
            material={glowBlue}
            position={[175.52, -849.85, 59.44]}
          />
          <mesh
            geometry={nodes.Sphere074.geometry}
            material={glowBlue}
            position={[-50.81, -991.6, 113.47]}
          />
          <mesh
            geometry={nodes.Sphere075.geometry}
            material={glowBlue}
            position={[49.21, -1100.24, -115.83]}
          />
          <mesh
            geometry={nodes.Sphere076.geometry}
            material={glowBlue}
            position={[18.26, -1199.68, 123.89]}
          />
          <mesh
            geometry={nodes.Sphere077.geometry}
            material={glowBlue}
            position={[-195.24, -552.33, -187.46]}
          />
          <mesh
            geometry={nodes.Sphere078.geometry}
            material={glowBlue}
            position={[-120.3, -722.86, 80.94]}
          />
          <mesh
            geometry={nodes.Sphere079.geometry}
            material={glowBlue}
            position={[-95.46, -1018.89, -146.5]}
          />
          <mesh
            geometry={nodes.Sphere080.geometry}
            material={glowBlue}
            position={[-117.61, -511.44, -33.52]}
          />
          <mesh
            geometry={nodes.Sphere081.geometry}
            material={glowBlue}
            position={[-45.4, -521.71, -140.27]}
          />
          <mesh
            geometry={nodes.Sphere082.geometry}
            material={glowBlue}
            position={[156.19, -311.69, 36.91]}
          />
          <mesh
            geometry={nodes.Sphere083.geometry}
            material={glowBlue}
            position={[-148.26, -473.37, -65.26]}
          />
          <mesh
            geometry={nodes.Sphere084.geometry}
            material={glowBlue}
            position={[-134.58, -247.57, 176.44]}
          />
          <mesh
            geometry={nodes.Sphere085.geometry}
            material={glowBlue}
            position={[-57.65, -810.83, -130.66]}
          />
          <mesh
            geometry={nodes.Sphere086.geometry}
            material={glowBlue}
            position={[1.06, -1043.1, 109.74]}
          />
          <mesh
            geometry={nodes.Sphere087.geometry}
            material={glowBlue}
            position={[96.47, -869.96, -153.57]}
          />
          <mesh
            geometry={nodes.Sphere088.geometry}
            material={glowBlue}
            position={[-54.6, -552.1, -97.46]}
          />
          <mesh
            geometry={nodes.Sphere089.geometry}
            material={glowBlue}
            position={[241.58, -488.92, 171.65]}
          />
          <mesh
            geometry={nodes.Sphere090.geometry}
            material={glowBlue}
            position={[-124.61, -962.49, -24.88]}
          />
          <mesh
            geometry={nodes.Sphere091.geometry}
            material={glowBlue}
            position={[7.4, -1139.42, -88.4]}
          />
          <mesh
            geometry={nodes.Sphere092.geometry}
            material={glowBlue}
            position={[-153.86, -975.55, -95.48]}
          />
          <mesh
            geometry={nodes.Sphere093.geometry}
            material={glowBlue}
            position={[21.51, -796.5, -190.86]}
          />
          <mesh
            geometry={nodes.Sphere094.geometry}
            material={glowBlue}
            position={[10.16, -419.48, -145.45]}
          />
          <mesh
            geometry={nodes.Sphere095.geometry}
            material={glowBlue}
            position={[102.65, -1265.46, 47.8]}
          />
          <mesh
            geometry={nodes.Sphere096.geometry}
            material={glowBlue}
            position={[-215.54, -544.24, 11.16]}
          />
          <mesh
            geometry={nodes.Sphere097.geometry}
            material={glowBlue}
            position={[32.5, -731.75, 127.87]}
          />
          <mesh
            geometry={nodes.Sphere098.geometry}
            material={glowBlue}
            position={[-30.58, -672.9, -287.81]}
          />
          <mesh
            geometry={nodes.Sphere099.geometry}
            material={glowBlue}
            position={[-116.14, -454.08, 200.74]}
          />
          <mesh
            geometry={nodes.Sphere100.geometry}
            material={glowBlue}
            position={[-106.2, -453.14, -6.26]}
          />
          <mesh
            geometry={nodes.Sphere101.geometry}
            material={glowBlue}
            position={[-146.48, -895.83, 58.5]}
          />
          <mesh
            geometry={nodes.Sphere102.geometry}
            material={glowBlue}
            position={[-113.62, -446.04, 40.08]}
          />
          <mesh
            geometry={nodes.Sphere103.geometry}
            material={glowBlue}
            position={[16.67, -297.4, 154.85]}
          />
          <mesh
            geometry={nodes.Sphere104.geometry}
            material={glowBlue}
            position={[48.12, -976.85, -110.43]}
          />
          <mesh
            geometry={nodes.Sphere105.geometry}
            material={glowBlue}
            position={[-49.91, -914.32, -83.54]}
          />
          <mesh
            geometry={nodes.Sphere106.geometry}
            material={glowBlue}
            position={[-201.45, -614.93, 81.1]}
          />
          <mesh
            geometry={nodes.Sphere107.geometry}
            material={glowBlue}
            position={[197.45, -749.53, -21.25]}
          />
          <mesh
            geometry={nodes.Sphere108.geometry}
            material={glowBlue}
            position={[109.99, -839.91, 34.16]}
          />
          <mesh
            geometry={nodes.Sphere109.geometry}
            material={glowBlue}
            position={[139.76, -799.04, -113.03]}
          />
          <mesh
            geometry={nodes.Sphere110.geometry}
            material={glowBlue}
            position={[-2.55, -352.39, -137.97]}
          />
          <mesh
            geometry={nodes.Sphere111.geometry}
            material={glowBlue}
            position={[-65.41, -591.91, -50.49]}
          />
          <mesh
            geometry={nodes.Sphere112.geometry}
            material={glowBlue}
            position={[77.05, -570.3, 256.9]}
          />
          <mesh
            geometry={nodes.Sphere113.geometry}
            material={glowBlue}
            position={[-112.63, -797.55, 57.34]}
          />
          <mesh
            geometry={nodes.Sphere114.geometry}
            material={glowBlue}
            position={[-37.32, -1024.83, 106.24]}
          />
          <mesh
            geometry={nodes.Sphere115.geometry}
            material={glowBlue}
            position={[270.98, -274.96, 139.58]}
          />
          <mesh
            geometry={nodes.Sphere116.geometry}
            material={glowBlue}
            position={[-31.53, -723.01, 157.66]}
          />
          <mesh
            geometry={nodes.Sphere117.geometry}
            material={glowBlue}
            position={[224.19, -607.34, -4.28]}
          />
          <mesh
            geometry={nodes.Sphere118.geometry}
            material={glowBlue}
            position={[69.23, -387.83, -108.12]}
          />
          <mesh
            geometry={nodes.Sphere119.geometry}
            material={glowBlue}
            position={[109.44, -527.7, -34.68]}
          />
          <mesh
            geometry={nodes.Sphere120.geometry}
            material={glowBlue}
            position={[-91.42, -524.81, 209]}
          />
          <mesh
            geometry={nodes.Sphere121.geometry}
            material={glowBlue}
            position={[-145.78, -866.2, 103.57]}
          />
        </mesh>
        <mesh
          geometry={nodes.Photorezeptor.geometry}
          material={materials["default"]}
          position={[0, 0, 80.28]}
        />
        <mesh
          geometry={nodes.Photorezeptor1.geometry}
          material={materials["Mat.1"]}
          position={[0, 0, 71.59]}
        />
        <mesh
          geometry={nodes.Platine.geometry}
          material={materials["default"]}
          position={[0, 0, 128.14]}
        />
        <mesh
          geometry={nodes.Ring1.geometry}
          material={materials["Metal_-_Chrome"]}
          position={[0, 0, 283.03]}
          rotation={[0, 0, 1.23]}>
          <mesh
            geometry={nodes.Ring002.geometry}
            material={materials["Mat.014"]}
            position={[-91.88, 114.64, 0]}
            rotation={[-Math.PI / 2, 0.9, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Ring003.geometry}
              material={materials["Mat.014"]}
              position={[0, 146.7, 146.92]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring004.geometry}
              material={materials["Mat.014"]}
              position={[0, 239.99, 113.67]}
              rotation={[-2.26, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring005.geometry}
              material={materials["Mat.014"]}
              position={[0, 33.38, 93.25]}
              rotation={[-0.69, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring006.geometry}
              material={materials["Mat.014"]}
              position={[0, 147.13, -146.92]}
              rotation={[1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring007.geometry}
              material={materials["Mat.014"]}
              position={[0, 53.84, -113.67]}
              rotation={[0.88, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring008.geometry}
              material={materials["Mat.014"]}
              position={[0, 293.82, 1.76]}
              rotation={[-3.13, 0, 0]}
            />
            <mesh
              geometry={nodes.Ring009.geometry}
              material={materials["Mat.014"]}
              position={[0, 261.56, -91.88]}
              rotation={[2.47, 0, 0]}
            />
          </mesh>
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/cyberEyeDraco.gltf");
